site_name: ""
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: "https://github.com/gruke-build/src"
repo_name: "gruke-build/src"
edit_uri: ""
theme:
  name: material
  logo: logo.png
  favicon: favicon.ico
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - search.share
  palette:
    - scheme: slate
      primary: teal
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

plugins:
  - asciinema-player

extra_css: 
    - css/image-hide-based-on-theme.css

extra_javascript:
    - js/readthedocs-search.js

nav:
  - Home: 
    - Info: index.md
    - Introduction: introduction.md
  - "Getting Started":
    - Installation: getting-started/installation.md
    - "Build Setup": getting-started/setup.md
    - "Build Execution": getting-started/execution.md
    - Telemetry: getting-started/telemetry.md
  - Fundamentals:
    - Builds: fundamentals/builds.md
    - Targets: fundamentals/targets.md
    - Parameters: fundamentals/parameters.md
    - Logging: fundamentals/logging.md
    - Assertions: fundamentals/assertions.md
  - "Common Tasks":
    - "Constructing Paths": common/paths.md
    - "Repository Insights": common/repository.md
    - "Data Serialization": common/serialization.md
    - "Versioning Artifacts": common/versioning.md
    - "Solution & Project Model": common/solution-project-model.md
    - "Executing CLI Tools": common/cli-tools.md
    - "Archive Compression": common/compression.md
    - "Chats & Social Media": common/chats.md
  - "Build Sharing":
    - "Global Builds": sharing/global-builds.md
    - "Build Components": sharing/build-components.md
  - "CI/CD Support":
    - AppVeyor: cicd/appveyor.md
    - "Azure Pipelines": cicd/azure-pipelines.md
    - BitBucket: cicd/bitbucket.md
    - "GitHub Actions": cicd/github-actions.md
    - GitLab: cicd/gitlab.md
    - Jenkins: cicd/jenkins.md
    - "Space Automation": cicd/space-automation.md
    - "TeamCity": cicd/teamcity.md
  - "Global Tool":
    - "Shell Completion": global-tool/shell-completion.md
    - "Adding NuGet Packages": global-tool/packages.md
    - "Managing Secrets": global-tool/secrets.md
    - "Navigation": global-tool/navigation.md
    - "Converting from Cake": global-tool/cake.md
  - "C# API": https://nuke.greemdev.net/docfx/api

markdown_extensions:
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc
extra:
  social:
    - icon: fontawesome/regular/heart
      link: https://github.com/sponsors/GreemDev
      name: Support the Project
